import { describe, expect, it } from "vitest";
import { createRequestFromModelfile, isPathLikeFromSource } from "./modelfile";

describe("Modelfile create request parser", () => {
  it("creates a structured API request from a Modelfile", () => {
    expect(
      createRequestFromModelfile(
        "mario",
        `FROM llama3.2
PARAMETER temperature 0.7
PARAMETER num_ctx 4096
PARAMETER stop "<|eot_id|>"
PARAMETER stop "AI assistant:"
SYSTEM """You are Mario.
Keep answers short."""
MESSAGE user Is Toronto in Canada?
MESSAGE assistant yes`
      )
    ).toEqual({
      model: "mario",
      from: "llama3.2",
      parameters: {
        temperature: 0.7,
        num_ctx: 4096,
        stop: ["<|eot_id|>", "AI assistant:"]
      },
      system: "You are Mario.\nKeep answers short.",
      messages: [
        { role: "user", content: "Is Toronto in Canada?" },
        { role: "assistant", content: "yes" }
      ]
    });
  });

  it("uses the generated replacement FROM hint when the active FROM points at a blob path", () => {
    expect(
      createRequestFromModelfile(
        "custom-llama",
        `# Modelfile generated by "ollama show"
# To build a new Modelfile based on this, replace FROM with:
# FROM llama3.2:latest

FROM C:\\Users\\clint\\.ollama\\models\\blobs\\sha256-abc
PARAMETER temperature 0.3`
      )
    ).toMatchObject({
      model: "custom-llama",
      from: "llama3.2:latest",
      parameters: { temperature: 0.3 }
    });
  });

  it("rejects path-based FROM values without a safe model-name replacement", () => {
    expect(() => createRequestFromModelfile("custom", "FROM ./model.gguf")).toThrow(
      /existing model name in FROM/
    );
  });

  it("detects local path sources without blocking namespaced model names", () => {
    expect(isPathLikeFromSource("x/flux2-klein")).toBe(false);
    expect(isPathLikeFromSource("/Users/me/.ollama/models/blobs/sha256-abc")).toBe(true);
    expect(isPathLikeFromSource("C:\\Users\\me\\.ollama\\models\\blobs\\sha256-abc")).toBe(true);
  });
});
